// src/components/select/NovaOptGroup.jsx
import Storage from '@/utils/storage';

export default {
  name: 'NovaOptGroup',
  inject: ['NovaSelect'],
  isSelectOptGroup: true,
  props: {
    prefixedClass: {
      type: String,
      default: `${Storage.prefix}-select`
    },
    label: {
      type: String,
      default: ''
    }
  },
  render() {
    const { $slots } = this;
    const children = $slots.default;

    return <div>{children}</div>;
  }
};

// src/components/select/NovaOptGroup.vue
<template>
  <div class="nova-select-option-group" v-bind="$attrs" v-on="$listeners">
    <div
      class="nova-select-option-group-label"
      v-if="this.NovaSelect.dropdownLoaded"
    >
      <slot name="label">
        {{ label }}
      </slot>
    </div>
    <div class="nova-select-option-group-content">
      <slot></slot>
    </div>
  </div>
</template>

<script>
export default {
  name: 'NovaOptGroup',
  inject: ['NovaSelect'],
  props: {
    label: {
      type: String
    }
  }
};
</script>
