// src/components/locale/NovaLocale.vue
<template>
  <div class="nova-ui-locale" v-bind="$attrs" v-on="$listeners">
    <slot></slot>
  </div>
</template>

<script>
import zhCN from '@/locales/lang/zh-CN';
import holiday from '@/locales/holiday/china';

export default {
  name: 'NovaLocale',
  provide() {
    return {
      NovaLocale: this
    };
  },
  props: {
    holiday: {
      type: Object,
      default: () => {
        return holiday;
      }
    },
    locale: {
      type: Object,
      default: () => {
        return zhCN;
      }
    }
  }
};
</script>

<style lang="less">
.nova-ui-locale {
  vertical-align: top;
  display: inline-block;
}
</style>

// src/components/locale/NovaLocale.jsx
import zhCN from '@/locales/lang/zh-CN';
import holiday from '@/locales/holiday/china';

export default {
  name: 'NovaLocale',
  provide() {
    return {
      NovaLocale: this
    };
  },
  props: {
    block: {
      type: Boolean,
      default: true
    },
    holiday: {
      type: Object,
      default: () => {
        return holiday;
      }
    },
    locale: {
      type: Object,
      default: () => {
        return zhCN;
      }
    }
  },
  render() {
    const { block, $attrs, $slots, $listeners } = this;

    const classList = { 'nova-locale': true, 'nova-locale-block': block };

    const children = $slots.default;

    const localeProps = {
      class: classList,
      attrs: {
        ...$attrs
      },
      on: {
        ...$listeners
      }
    };

    return <div {...localeProps}>{children}</div>;
  }
};
